---
title: "Evaluations"
---

**Instructions for the various evaluations and assessments will be posted here as the semester progresses, so please bookmark this site.**

## [Syllabus Quiz](syllabus-quiz.html) (10 points)
There will be a syllabus quiz on Tuesday, January 30. Ten questions, ten points.

## Participation/Quizzes/Check-ins (140 points)

Throughout the semester, I will have short activities, participation quizzes, and check-ins. I use these to track progress and participation in the course. Each will generally be worth 10 points, for a total of 140 points.

## Labs (500 points) and [Map Tutorials](map-tutorials.html) (150 points)
Labs will consist of exercises that provide a means to put theory as presented through the lectures and reading material into practice. The labs are software intensive utilizing ESRI ArcGIS Pro and sometimes Microsoft Excel. There will be instructions for each lab that outline the learning objectives and the steps that should be taken to complete the project. Although some steps will be written-up in detail, there will not be explicit instructions for every button-click in the software. The student is responsible for applying the on-screen demonstrations, technique videos, and outside resources that will be introduced by the instructor. Each lab will be documented in a report that follows the standard scientific format. This includes the following sections: Introduction, Methods, Results, Discussion, Conclusion and References. We will cover how to write the various sections of the report and build up to a complete paper for the final projects. The maps, tables, and graphs generated in labs are to be used as figures for the reports. **Always place maps as large as possible, one to a page, rotated if necessary.** A *Scientific Report Template* will be provided and must be used or points will be deducted. **Each lab write-up is worth 100 points.**

Three shorter [**Map Tutorials**](map-tutorials.html) will round out your GIS skill set, and/or will serve as an introduction to ArcPro for those of you who have taken past courses using the legacy ArcMap software. **Each map tutorial write-up is worth 50 points.**

All labs and map tutorials will be submitted into separate Microsoft Forms in **Microsoft Word or PDF formats only**. Please see the individual assignment pages for specific due dates and instructions.

## Resource Notebook (100 points)
Each student is required to create a digital notebook filled with the content featured in the class. The purpose of this notebook is to give the student a "take-away" resource of GIS techniques for future mapping projects. On the class server ("T:\\\\ Drive"), under your personal student folder, create a sub-folder called "Resources", within which you should start documenting and useful information you glean from this course. You may develop your resource notebook in whatever organization you like, but a possible organization would be sub-folders named Readings, Lectures, Map Tutorials, and Labs. Do not wait until the last minute to put together the notebook. Start adding content the first week and continue to keep it organized throughout the semester. It will be your one-stop reference for the theory and techniques covered in class. Extra material can include exam study guides and other resources from the web. The notebook will be checked toward the end of the semester for a grade worth 100 points.

## Midterm Exam (200 points) and Final Exam (250 points)
You are responsible for knowing everything read or said in this class. Exams will have several sections starting with multiple choice and true or false questions. Then there will be a definition matching section based on the glossary terms in the readings. Finally, essay questions will require you to evaluate a map, outline the theory behind a GIS analysis technique, or discuss other course content. **The final exam is comprehensive**, including content evaluated by the midterm exam. The Final Exam is longer and is worth more points (250) than the Midterm (200). Exams are closed-book.

## Final Group Projects (600 points)
A semester-long assignment, the group GIS project requires the students to identify a unique resource management problem that can be answered with GIS analysis. Each group must submit a project proposal following a format that will be discussed in class. As a group, you will develop a research question, review the literature for what techniques have been applied previously, decide what data is required, and design the methods for your analysis. You will document your analysis in an ESRI StoryMap that will roughly follow the scientific format used in the lab reports with the addition of a small literature review. You will include maps, graphs, tables, and figures that support your research and its results. The project design, workflow and conclusions will be presented to the class at the end of the semester. The 600 point project is worth 30 percent of your total grade and is divided as follows:

| Component  | Points  |
|--------|--------|
| Project Proposal     | 100 pts. |
| Final Group StoryMap | 400 pts. |
| Presentation         | 100 pts. |
