---
format:
  revealjs: 
    theme: dark
    embed-resources: true
    slide-number: true
    preview-links: auto
    css: ["css/ath-slides.css", "css/ath-inferno-fonts.css", "css/animate.css"]
editor_options: 
  chunk_output_type: console
---

# Group GIS Project

::: {.class-info}

Kyle Bocinsky

::: light

FORS350 / GPHY488<br>(Forestry) Applications of GIS<br>University of Montana<br>
WA Franke College of Forestry & Conservation

:::

:::

## Project Overview
- Identify unique resource management or environmental planning challenge
- Submit a project proposal
- Use GIS analysis and create an ESRI StoryMap to communicate findings

## Purpose of the Project
- Practice designing, organizing, and executing a research project using ArcGIS
- Develop communication skills in an attractive and interactive format
- Emphasize group-based work for professional skill development

## Project Components and Grading
- Project Proposal (100 pts.) - Due Friday, March 29, 11:59 PM
- Final Group StoryMap (400 pts.) - Due Friday, April 26, 11:59 PM
- StoryMap Presentation (100 pts.) - In class, April 30 & May 2

## Project Proposal Sections
- Introduction (~250-500 words)
- Problem Statement (~500 words)
- Contextual Framework (~500-1000 words)
- Proposed Methods (~250-500 words)

## Final Group StoryMap
- Components: ArcGIS Pro Project and ArcGIS StoryMap
- Document databases, toolboxes, and maps in ArcGIS Pro Project
- Develop an engaging ArcGIS StoryMap
  - Introduction, Contextual Framework, Methods, Results, Discussion, Conclusion

## Peer Feedback
- 360-degree peer feedback process: assess yourself and  your teammates on contributions to the project
- Twice during the course of the project:
  - With Project Proposal
  - With StoryMap Presentation
- Meant to provide constructive feedback, encourage equitable contributions to the project, and acknowledge exceptional collaboration

## QUESTIONS?
