---
title: "Schedule"
sidebar: false
toc: false
page-layout: full
editor_options: 
  chunk_output_type: console
---

::: {.schedule-page}


- [**Content**](/content/) ({{< fa person-chalkboard >}}): This page contains the readings, slides, and lecture notes for the week.
- **Readings** ({{< fa book >}}): This page brings you directly to the required readings for the day.
- [**Evaluations**](/evaluations/) ({{< fa pen-ruler >}}): This page contains the instructions for each evaluation.

```{r build-table, include=FALSE}
library(tidyverse)
library(glue)
library(knitr)
library(kableExtra)
Sys.setlocale("LC_TIME", "en_CA.UTF-8")
withr::with_dir(here::here(), {
  targets::tar_load(schedule_file)
})

if(file.exists(schedule_file)){
  schedule_raw <- read_csv(schedule_file)
}else{
  schedule_raw <- read_csv("schedule.csv")
}


schedule <- schedule_raw %>% 
  mutate(date = lubridate::mdy(date),
         date_end = lubridate::mdy(date_end)) %>%
  mutate(group = fct_inorder(group)) %>% 
  mutate(subgroup = fct_inorder(subgroup)) %>% 
  mutate(var_title = ifelse(!is.na(content), 
                            glue('<span class="content-title">{title}</span>'),
                            glue('{title}'))) %>% 
  mutate(var_deadline = ifelse(!is.na(deadline),
                               glue('&emsp;&emsp;<small>(submit by {deadline})</small>'),
                               "")) %>%
  mutate(var_content = ifelse(!is.na(content),
                              glue('<a href="/content/{content}.qmd"><i class="fa-solid fa-person-chalkboard fa-lg"></i></a>'),
                              glue('<font color="#e9ecef"><i class="fa-solid fa-person-chalkboard fa-lg"></i></font>'))) %>%
  mutate(var_readings = ifelse(!is.na(readings),
                              glue('<a href="/content/{content}.html#{readings}"><i class="fa-solid fa-book fa-lg"></i></a>'),
                              glue('<font color="#e9ecef"><i class="fa-solid fa-book fa-lg"></i></font>'))) %>%
  mutate(var_evaluations = ifelse(!is.na(evaluations),
                                 glue('<a href="/evaluations/{evaluations}.qmd"><i class="fa-solid fa-pen-ruler fa-lg"></i></a>'),
                                 glue('<font color="#e9ecef"><i class="fa-solid fa-pen-ruler fa-lg"></i></font>'))) %>%
  mutate(col_date = ifelse(is.na(date_end),
                           glue('<strong>{format(date, "%B %e")}</strong>'),
                           glue('<strong>{format(date, "%B %e")}</strong>–<strong>{format(date_end, "%B %e")}</strong>'))) %>% 
  mutate(col_title = glue('{var_title}{var_deadline}')) %>% 
  mutate(col_content = var_content,
         col_readings = var_readings,
         col_evaluations = var_evaluations)

schedule_nested <- schedule %>% 
  select(group, subgroup, 
         ` ` = col_date, Title = col_title, Content = col_content, 
         Readings = col_readings, Evaluations = col_evaluations) %>% 
  group_by(group) %>% 
  nest() %>% 
  mutate(subgroup_count = map(data, ~count(.x, subgroup)),
         subgroup_index = map(subgroup_count, ~{
           .x %>% pull(n) %>% set_names(.x$subgroup)
         }))

show_table <- function(group_id) {
  # Add a heading
  cat(as.character(paste("\n\n###", schedule_nested$group[[group_id]], "\n\n")))
  # Make the table
  tbl <- schedule_nested$data[[group_id]] %>%
    select(-subgroup) %>% 
    kbl(escape = FALSE, align = "rlccc", table.attr = 'class="schedule-table"') %>% 
    kable_styling() %>% 
    column_spec(1, width = "20%", extra_css = "padding-right: 20px;") %>% 
    column_spec(2, width = "50%") %>% 
    column_spec(3:5, width = "10%") %>% 
    pack_rows(index = schedule_nested$subgroup_index[[group_id]],
              label_row_css = "border-bottom: 2px solid #000000;")
  
  cat(tbl)
}
```

```{r show-table, echo=FALSE, results="asis"}
walk(seq(1, nrow(schedule_nested)), ~show_table(.x))
```

:::
